apiVersion: apps/v1
kind: Deployment
metadata:
  name: middle-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middle
  template:
    metadata:
      labels:
        app: middle
    spec:
      containers:
      - name: middle
        image: valmikiops/mid:0.3
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "database-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "demo"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: APP_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: middle-service
spec:
  type: ClusterIP
  selector:
    app: middle
  ports:
    - port: 8080
      targetPort: 8080

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: middle-service
# spec:
#   type: NodePort
#   selector:
#     app: middle
#   ports:
#     - port: 8080
#       targetPort: 8080
#       nodePort: 30081
